# FPN, Unet or DeepLab
arch: FPN
backbone: efficientnet-b3
pretrained: true

# resize images to this size on the fly
image_size: 320
# crop to this fraction of image_size
crop_size: 0.9

# optimizer settings
optim: adam
lr: 0.001
weight_decay: 0.01
batch_size: 32

# scheduler settings
gamma: 0.96

# data augmentation
aug_prob: 0.4
strong_aug: true
max_cutout: 0
